### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by kaynnan** [Escodoo/purchase-addons#12]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] purchase_quotation_report_tax_removal
- [x] purchase_readonly_restrictions
- [x] purchase_requisition_order_line
- [x] supplier_quality_index

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list
